# Generated by Django 3.0.8 on 2020-07-19 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.CharField(max_length=255)),
                ('animal', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=255)),
                ('peso', models.CharField(blank=True, max_length=255)),
                ('especie', models.CharField(blank=True, max_length=255)),
                ('idade', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True)),
                ('mostrar', models.BooleanField(default=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Plano')),
            ],
        ),
    ]
