# Generated by Django 3.0.8 on 2020-07-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200719_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacina',
            options={},
        ),
    ]
