# Generated by Django 3.0.8 on 2020-07-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_vacinas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacinas',
            new_name='Vacina',
        ),
    ]
