# Generated by Django 3.0.8 on 2020-07-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200719_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacina',
            options={'verbose_name': 'Vacina', 'verbose_name_plural': 'Vacinas'},
        ),
    ]
