# Generated by Django 3.0.8 on 2020-07-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20200719_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirurgia', models.CharField(max_length=255)),
                ('data', models.DateField(blank=True)),
                ('descricao_da_cirurgia', models.TextField(blank=True, verbose_name='Descrição da cirurgia')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
    ]
