# Generated by Django 3.0.8 on 2020-07-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cirurgia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Plano'),
        ),
    ]
