# Generated by Django 3.0.8 on 2020-07-30 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20200730_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='Nenhum', max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=255, verbose_name='Raça')),
                ('peso', models.CharField(blank=True, max_length=255)),
                ('especie', models.CharField(blank=True, max_length=255, verbose_name='Espécie')),
                ('idade', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('mostrar', models.BooleanField(default=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Dono')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Plano')),
            ],
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Animal'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Animal'),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Animal'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
