# Generated by Django 3.0.8 on 2020-07-31 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200730_0427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dono',
            new_name='Tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='data_criacao',
            new_name='data_criacao_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='descricao',
            new_name='descricao_tutor',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='dono',
        ),
        migrations.AddField(
            model_name='animal',
            name='microchip_local',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localização do Microchip'),
        ),
        migrations.AddField(
            model_name='animal',
            name='microchip_numero',
            field=models.CharField(blank=True, max_length=255, verbose_name='Número do Microchip'),
        ),
        migrations.AddField(
            model_name='animal',
            name='pelagem',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='animal',
            name='porte',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clientes.Tutor'),
            preserve_default=False,
        ),
    ]
