# Generated by Django 3.0.8 on 2020-08-16 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20200816_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='idade',
        ),
        migrations.AddField(
            model_name='animal',
            name='data_nascimento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
    ]
