# Generated by Django 3.0.8 on 2020-08-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_auto_20200816_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='cirurgia',
            field=models.CharField(blank=True, default=' - ', max_length=255),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='consulta',
            field=models.CharField(blank=True, default=' - ', max_length=255),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='vacina',
            field=models.CharField(blank=True, default=' - ', max_length=255),
        ),
    ]
